// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijnmGm8amUNJ2x-758hqgFEWBtTKt9QM',
    appId: '1:356274277653:web:470b2ac0a748c77e776d1c',
    messagingSenderId: '356274277653',
    projectId: 'travel-example-starter-25ctb6',
    authDomain: 'travel-example-starter-25ctb6.firebaseapp.com',
    storageBucket: 'travel-example-starter-25ctb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0cnmNNqwx9rW2fY6V8zeaIggCs8ll0vk',
    appId: '1:356274277653:android:7fc8f773f8b761ae776d1c',
    messagingSenderId: '356274277653',
    projectId: 'travel-example-starter-25ctb6',
    storageBucket: 'travel-example-starter-25ctb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTkr50D689eoWe1vJTkOJ7CzOCL4Keh0',
    appId: '1:356274277653:ios:e6ceae5137aa7eec776d1c',
    messagingSenderId: '356274277653',
    projectId: 'travel-example-starter-25ctb6',
    storageBucket: 'travel-example-starter-25ctb6.appspot.com',
    iosBundleId: 'com.example.flutterFlowTravelExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTkr50D689eoWe1vJTkOJ7CzOCL4Keh0',
    appId: '1:356274277653:ios:e6ceae5137aa7eec776d1c',
    messagingSenderId: '356274277653',
    projectId: 'travel-example-starter-25ctb6',
    storageBucket: 'travel-example-starter-25ctb6.appspot.com',
    iosBundleId: 'com.example.flutterFlowTravelExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAijnmGm8amUNJ2x-758hqgFEWBtTKt9QM',
    appId: '1:356274277653:web:bbd5f9417d88b363776d1c',
    messagingSenderId: '356274277653',
    projectId: 'travel-example-starter-25ctb6',
    authDomain: 'travel-example-starter-25ctb6.firebaseapp.com',
    storageBucket: 'travel-example-starter-25ctb6.appspot.com',
  );
}
